### PR TITLE
Added features

### PR DESCRIPTION
**Pull request by GrbavaCigla**
#14

### CODE REVIEW

**Comment by GrbavaCigla** [comment]
For some reason hacktoberfest says it is invalid.

**Comment by GrbavaCigla** [comment]
Can you add hacktoberfest topic please? My pull request wont count without it. Thanks.

**Comment by brilam** [comment]
@GrbavaCigla I have added a label for hacktoberfest. Does that work right now? Or did I misunderstand?

**Comment by GrbavaCigla** [comment]
> Ineligible Repository
Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate.
You have to add repository topic:
image

**Comment by brilam** [comment]
Sorry about that. I am new to maintaining a repo for Hacktoberfest. I've added it. Can you double check if everything is fine? If so, I'd be happy to merge your pull request.

**Comment by GrbavaCigla** [comment]
I am learning it too :). They changed that bit because of spammers. It works now, you can merge it if you want, if not, suggest changes. Thanks!

**Comment by GrbavaCigla** [comment]
I am reminding you in case you forgot to merge :)

**Comment by brilam** [comment]
Merged. Thanks for the contribution 👍

**Pull request merged**
